name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Copy .env File
        run: | 
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "HOST=${{ secrets.HOST }}" >> .env
          echo "CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}" >> .env
          echo "COMMON_RATE_LIMIT_WINDOW_MS=${{ secrets.COMMON_RATE_LIMIT_WINDOW_MS }}" >> .env
          echo "COMMON_RATE_LIMIT_MAX_REQUESTS=${{ secrets.COMMON_RATE_LIMIT_MAX_REQUESTS }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "Running tests with secret: $SECRET_KEY"
          
      # - name: Install Dependencies
      #   run: npm install
      
      # - name: Build Project
      #   run: npm run build
      
      - name: View .env file (for debugging)
        run: cat .env
      
      # - name: Start Server
      #   run: npm run start

      # - name: Deploy to Azure
      #   uses: azure/webapps-deploy@v1
      #   with:
      #     app-name: 'github-favourites'
      #     slot: 'stage'
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     resource-group: 'github-favourites_group'
      #     zip-path: './'
