name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install
      
      - name: Build Project
        run: npm run build
      
      - name: Start Server
        run: npm run start

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v1
        with:
          app-name: 'github-favourites'
          slot: 'stage'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          resource-group: 'github-favourites_group'
          zip-path: './'
